### ISSUE TITLE
parse_label assert error

### ISSUE THREAD

**Issue by andrecavalcante** [brianhuang1019/FCN-pytorch#3]
Hi, 
why does CamVid_utils generate the following error on some files such as 0016E5_08460_L.png

> Traceback (most recent call last):
>   File "python/CamVid_utils.py", line 141, in <module>
>     parse_label()
>   File "python/CamVid_utils.py", line 122, in parse_label
>     assert color2label[tuple(color)] == test_ans[idx]
> AssertionError

**Comment by andrecavalcante** [comment]
Thank you!
